
export default english = {
    //profile: "Profile",
    profile: "Profile",
    yourplan: "Your Plan",
    progress: "Progress",
    grocerylist: "Grocery List",
    LNFshop: "LNF Shop",
    lang: "Language",
    goals: "Goals",
    gratitude: "Gratitude",
    chatwithcoach: "Message",
    reminder: "Reminder",
    blog: "Blog",
    customersupport: "Customer Support",
    faq: "FAQ",
    leadershipboard: "Leadership Board",
    medicalinformation: "Medical Information",
    ChangeYourCoach: "Change Your Coach",
    deleteaccount: "Delete Account",
    logout: "Logout",
    TermsandConditions: "Terms & Conditions",
    hello: "Hello",
    Upgrade: "Upgrade",
    UnlocktheCoaches: "Unlock the Coaches",
    Unlockover100mealandexerciseplans: "Unlock over 100+ meal and exercise plans",
    Monitoryourhealth: "Monitor your health",
    FirstConsultationfree: "First Consultation free",
    Unlimitedchatwithcoach: "Unlimited chat with coach",
    ConsultationCallspermonth: "1 Consultation Call per month",
    Redeem: "Redeem",
    pointstobookextraconsultation: "points to book extra consultation",
    ChooseYourPlan: " Choose Your Plan",
    Bythisupgradeyouwillgetallfeatures: "By this upgrade, you will get all features",
    UpgradePlan: "Upgrade Plan",
    MealPlan: "Nutrition Plan",
    ExcercisesPlan: "Fitness Plan",
    Plans: "Plans",
    Coach: "Coach",
    Doctor: "Doctor",
    YourPersonalHealthAssistant: "Your Personal Health Assistant",
    AddRatings: "Rate your experience",
    Morecallispending: "1 More call is pending",
    Scheduleacall: "Schedule a call",
    MyProfile: "My Profile",
    LastUpdatedat: "Last Updated at",
    TotalPoints: "Total Points",
    Bio: "Bio",
    Location: "Location",
    BasicInformation: "Basic Information",
    PaymentDetails: "Payment Details",
    Writesomethingaboutyourself: "Write something about yourself",
    HeightWeightAgeGenderActivity: "Height, Weight, Age, Gender, Activity ",
    YourPaymentDetails: "Your Payment Details",
    EditProfile: "Edit Profile",
    Name: "Name",
    Foodtype: "Food type",
    Exerciseintensity: "Exercise intensity",
    Height: "Height",
    Weight: "Weight ",
    Age: "Age",
    Submit: "Submit",
    Skip: "Skip",
    Ok: "Ok",
    ElitePlan: "Elite Plan",
    CustomerSupport: "Customer Support",
    HavingabadDay: "Having a Bad Day?",
    Pleaseentergratitude: "I am grateful for --",
    CustSupportText: "Please fill the form below and we will get back to you as soon as possible.",
    DontworryThefuturebelongstothosewhobelieveinthebeautyoftheirdreams: "Don't worry! The future belongs to those who believe in the beauty of their dreams.।",
    RelaxThinkoftomorrow: "Relax! Think of tomorrow, the past can't be mended.।",
    NoworriesYesterday: "No worries! Yesterday is not ours to recover, but tomorrow is ours to win or lose.।",
    Itsok: "It's ok if today wasn't your day. Tomorrow is a new day.।",
    NoProblem: "No Problem! Tomorrow will be different.।",
    Good: "Good! But you can still do better।",
    YouaregettingcloserKeepitup: "You're getting closer. Keep it up।",
    GreatThink: "Great! Think you can and you can do it.Your thoughts are your life.।",
    Motivate: "Motivate yourself, you can be great।",
    GoodBeall: "Good! Be all that you can be.You can be great।",
    WellDoneKeepItUp: "Well done! Keep it up।",
    Congratulationssoveryproudofyou: "Congratulations! We’re so very proud of you!",
    CongratulationsTodayisyourday: "Congratulations! Today is your day. You’re off to great places. You’re off and away!",
    Cheers: "Cheers! The fruit of your own hard work is the sweetest.",
    ExcerciseProgress: "Excercise Progress",
    HydrationProgress: "Hydration Progress",
    SleepProgress: "Sleep Progress",
    MonetringProgress: "Monitor Progress",
    FastingProgress: "Fasting Progress",
    TodaysExcercise: `Today's Excercise`,
    TodaysMood: `Today's Mood`,
    TodaysMonitor: `Today's Monitoring`,
    Monitoring: "Monitoring",
    MoodTitle: "Mood",
    TodaysMeal: `Today's Meal`,
    TodaysSleep: `Today's Sleep`,
    Hydration: "Hydration",
    Fasting: "Fasting",
    Sleep: "Sleep",
    MoodText: "Mood",
    ExerciseText: "Exercise",
    WeeklyOverview: "Weekly Overview",
    ProgressChart: "Progress Chart",
    AllTime: "All Time",
    ThisMonth: "This Month",
    CurrentWeight: "Current Weight :",
    Cancel: "Cancel",
    YourWellnessWithOurFunctionalHealthPillars: "Your Wellness With Our Functional Health Pillars",
    DigitalMateToResetYourHabits: "DigitalMate To Reset Your Habits",
    PatientCenteredCare: "Patient - Centered Care ",
    TrackYourHealthMetricsRealtime: "Track Your Health Metrics Realtime",
    SetShareGoalWithYourPersonalCoaches: "Set & Share Goal With Your Personal Coaches",
    NoCalorieCounting: "No Calorie Counting",
    NoFillingFoodLogs: "No Filling Food Logs",
    NoFadDiet: "No Fad Diet",
    NoGym: "No Gym",
    GetNotified: "Get Notified ",
    GetStarted: "Get Started!",
    Next: "Next",
    pleasespecif: "Please Specify:",
    Register: "Register",
    Login: "Login",
    AreyouaCorporateUser: "Are you a Corporate User ?",
    Hey: " Hey!",
    Gladtomeetyou: "Glad to meet you",
    SignIn: "Sign In",
    Pleaseenteryourcredentialstocontinue: "Please enter your credentials to continue.",
    BysigningIaccepttheTermConditions: "By signing, I accept the Terms & Conditions",
    AgredSignIn: "Agree & Sign In",
    DonthaveanaccountCreateAccount: "Don't have an account? Create Account",
    EnterEmailIdPhoneNumber: "Enter Email Id/Phone Number",
    validmobilenumber: "Please enter the valid mobile number",
    validemailaddress: "Please enter the valid email address",
    EnterPassword: "Enter Password",
    EnterEmailId: "Enter Email Id",
    Enterphneno: "Enter Phone Number",
    ForgotPassword: "Forgot Password?",
    PleaseenteryourCorporateId: "Please enter your Corporate Id",
    Createyouraccount: "Create Your Account",
    Pleaseenteryourdetailstouseourapp: "Please enter your details to use our app",
    AgreeSignUp: "Agree & SignUp",
    EnterPassword: "Enter Password",
    ConfirmPassword: "Confirm Password",
    Pleaseenteryourname: "Please enter your name",
    Pleaseentervalidmobilenumber: "Please enter valid mobile number",
    Pleaseentervalidconfirmpassword: "Please enter valid confirm password",
    Pleasematchpasswordandconfirmpassword: "Please match password and confirm password",
    EnterNewPassword: "Enter New Password",
    Pleasematchemailaddressandemailaddress: "Please match email address and re-enter email address",
    Pleasematchmobilenumberandentermobilenumber: "Please match mobile number and re-enter mobile number",
    ReEnterYourEmailAddress: "Re-Enter Your Email Address",
    ReEnterYourMobileNumber: "Re-Enter Your Mobile Number",
    EnterMobileNumber: "Enter Your Mobile Number",
    ConfirmMobileNumber: "Confirm Your Mobile Number",
    EnterEmailAddress: "Enter Your Email Address",
    ConfirmEnterEmailAddress: "Confirm Your Email Address",
    Getnotificationsonyourphoneforanyalertsoractivities: "Get notifications on your phone for any alerts or activities",
    NameError: "Name can not be empty or contain Special Characters and Numbers!",
    MobileError: "Invalid Mobile Number!",
    ConfirmMobileError: "Mobile and Confirm Mobile must be same!",
    EmailError: "Invalid Email Address!",
    ConfirmEmailError: "Email and Confirm Email address must be same!",
    PasswordError: "Password can not be Empty!",
    RePasswordError: "Confirm password can not be Empty!",
    ConfirmError: "Password and Confirm Password must be same!",
    OTPVerification: "OTP Verification",
    DidnreceivecodeRequestagain: "Didn't receive code Request again",
    VerifySignIn: "Verify & Sign In",
    Wehavesentthecodeto: "We have sent the code to",
    AddReportLinks: "Add Report Links",
    AddFiles: "Add Files",
    UploadReports: "Upload Reports",
    YourLink: "Your Link Here...",
    Description: "Link Description..",
    UploadAttachments: "Upload Attachments",
    AttachmentDescriptionHere: "Attachment Description Here..",
    Youcannotupload5: "You can not upload more than 5 links for now",
    Youcannotuploadfiles1: "You can not upload more than 1 files for now",
    OpenCamera: "Open Camera",
    TotalPoints: "Total Points ",
    PointslastsyncedonToday: "Points last synced on Today",
    RedeemPoints: "Redeem Points",
    Datahasnotbeenentered: "Data has not been entered",
    Wellprovidenutritional: "We'll provide nutritional dense meal plans, easy to do daily exercise plans and articles that focus on learning not starving.",
    Proceed: "Proceed ",
    Welcome: "Welcome",
    PreparingYourPersonalizedMealPlan: "Preparing Your Personalized Meal Plan..",
    PreparingYourPersonalizedExercisePlan: "Preparing Your Personalized Exercise Plan..",
    AssigningyouaFunctionalCoach: "Assigning you a Functional Coach..",
    Ourpreventivehealth: "Our preventive health program based on Power of 7. It only takes 7 mins in a day.",
    Readytocommit: "Ready to commit to build to last habits|",
    RecommendedPlansforyou: "Recommended Plans for you",
    Basedonyourfitnessgoals: "Based on your fitness goals",
    CustomizableDietPlan: "Customizable Diet Plan",
    CustomizableReminders: "Customizable Reminders",
    YourCoachAssistantNutritionist: "Your Coach, Assistant, Nutritionist",
    OurAI: "Our AI Powered Plan to help you reach your Goal Weight",
    SmartDiet: "Smart Diet & Workout Plan",
    Starts: "Starts at ₹3500 per month",
    Skipfornow: "Skip for now >>",
    ExploreSmart: "Explore Smart",
    HealthIndex: "Health Index ",
    SwipeUpto: "Swipe Up to Answer Some Questions and Improve Your Health Index",
    SureLogout: "Are you sure, you want to Logout?",
    Logout: "Logout?",
    UpgradePlanText: "Currently you are a free user, you want to upgrade plan?",
    Top5goals: " Here are your top 5 goals:",
    Goals: "Goals",
    Add: "Add",
    Gratification: "Gratification",
    Gratefull: "Here are somethings that you're grateful about:",
    More: "More",
    PaymentGateway: "Payment Gateway",
    BasicSubscription: "basic subscription",
    SubscriptionAmount: "Subscription Amount",
    HaveACouponCode: "Have A Coupon Code?",
    BuyWith: "Buy With ",
    WaisttoHipRatioGraph: "Waist to Hip Ratio Graph",
    WaisttoHipRatio: "Waist to Hip Ratio ",
    AWaistCircumference: "A : Waist Circumference",
    BHipCircumference: "B : Hip Circumference",
    Waist: "Waist*",
    Hip: "Hip*",
    EnterYourWaistValueininch: "Enter Your Waist Value in inch",
    EnterYourHipValueininch: "Enter Your Hip Value in inch",
    YourWaistToHipRatiois: "Your Waist To Hip Ratio is: ",
    WHRGraph: "WHR Graph",
    WHR2: " WHR (Waist to Hip Ratio)",
    Psychology: "Psychology",
    PsychologyIndexhasbeensubmittedsuccessfully: "Psychology Index has been submitted successfully।",
    TotalScore: "Total Score",
    PsychologyValidation: "Kindly answers all questions!",
    Pain: "Pain ",
    Enterreson: "Enter the reason behind pain",
    RatingScale: "0 - 10 Pain Rating Scale ",
    None: "None",
    Mild: "Mild",
    Moderate: "Moderate",
    Severe: "Severe",
    Save: "Save",
    SwipeUp: "Swipe Up to Answer Some Questions and Improve Your Health Index",
    msg1: "Hey! This Screen keeps a record of Power of 7 on a regular basis!",
    msg2: "Choose From One of these Options According to your Progress today",
    msg3: "Then Press the Button here to Track your Weekly Progress",
    monitoringmsg3: "Weekly progress tracking feature will be available soon.",
    mealmsg1: "Plan ahead and keep track of what and when you are eating",
    mealmsg2: "You can go to plans",
    mealmsg3: "Meal Plan and then tap on",
    mealmsg4: "icon to replace the meal",
    mealmsg5: "Loved your meal? Let us know by clicking on",
    mealmsg6: "and we will repeat that meal for a week.",
    excercisemsg1: "Engage your body at a greater intensity than your usual level of daily activity.",
    excercisemsg2: "You can go to Plans",
    excercisemsg3: "Exercise Plan and then tap on",
    excercisemsg4: "icon to replace the",
    sleep: "Sleep is a period of rest that refreshes the mind and repairs the body.",
    hydration: "Providing an adequate amount of liquid (eg. water, tea, coffee etc) for tissues",
    Mood: "A conscious state of mind or predominant emotion.",
    fasting: "The abstention from food or drink or both for health, ritualistic, religious, or ethical purposes.",
    Observing: "Observation and recording of activities.",
    deleteacc: "Are you sure , you want to delete account?",
    AsyouarePregnant: "As you are Pregnant/Postpartum/Lactating, it is recommend to go for Paid Plan.",
    Diabetes: "As you are having Diabetes with Insulin, it is recommend you to go for Paid Plan.",
    Insulin: "As you are on Insulin, it is recommend you to go for Paid Plan",
    FeatureComingSoon: "Feature Coming Soon...",
    SetWHR: "Set Waist to Hip Ratio",
    YourWaisttoHipRatiois: "Your Waist to Hip Ratio is ",
    lowRisk: "Low Risk ",
    hignRisk: "High Risk ",
    YourReportsWillBeVisibleHere: "Your Reports Will Be Visible Here..",
    ThisfeatureforPaidCorporateUser: "This feature is only available for Paid/Corporate User. Please click OK to UPGRADE.",
    TrackFoodReminder: "Track Food Reminder",
    WaterReminder: "Water Reminder",
    ExerciseReminder: "Exercise Reminder",
    threeMealsatdifferenttimes: "3 Meals, at different times",
    Remindmeevery3Hour: "Remind me every 3 Hour",
    Remindmeeverydayat: "Remind me everyday at 7:30 PM",
    Next: "Next",
    Reminder: "Reminder",
    comments: "Comments (Optional)",
    Message: "Message",
    EnteryourGoal: "Enter your Goal",
    EnterGratification: "Enter your Gratification",
    GroceryList: "Your Grocery List",
    AddGroceries: "Add Groceries",
    GroceryListTitle: "Grocery List",
    totalpointstext: "Your 21 free reward points have been added to your total score",
    AsyouareaPaidUseryoucannotupgradeplan: "As you are a Paid/Corporate User, you cannot upgrade plan!",
    Profiling: "Profiling",
    Wehaveidealplanforyou: "We have ideal plan for you",
    LookslikeyoureinterestedingainingweightusingLNF: "Looks like you’re interested in gaining weight using LNF.",
    LookslikeyouinterestedinlosingweightusingLNF: "Looks like you’re interested in losing weight using LNF.",
    LNFisnotcurrentlydesignedtoreachtheenteredgoalweight: "LNF is not currently designed to reach the entered goal weight, Your target weight must be in between-",
    PleaseedityourTargetweighttoContinue: "Please edit your Target weight to Continue.",
    FreeUser: "Free User",
    paidUser: "Paid User",
    Select: "Select",
    CoporateIDEroor: "Corporate Id can not be empty!",
    LowGIFruitsandVegatables: "Low GI Fruits and Vegatables",
    callmsg: "Can I schedule a call for you?",
    bysignin: "By signing, I accept the, ",
    termsandcondition: "Terms & Conditions",
    donthaveanaccount: "Don't have an account? ",
    craeteone: "Create Account",
    didnotreceivecode: "Didn't receive the code? ",
    requestagain: "Request again",
    letsGo: "Let's Go",
    and: "and",
    privacypolicy: "Privacy Policy, ",
    includingusage: "including usage of Cookies",
    forgetpassword: "Forgot Password!",
    forgetmailmsg: "We will send the verification link to reset password to your registered email address. Please check your inbox.",
    freeuser: "Free User",
    paiduser: "Paid User",
    corporate: "Corporate",
    hindi: "Hindi",
    english: "English",
    //freecoachmsg: "To use personal coaching, please UPGRADE.\nThen we connect you with one of our Senior Functional coaches to understand your fitness goals, lifestyle, and offer help and guidance.",
    freecoachmsg: "To use  personal coaching, please click OK to UPGRADE.\nThen we shall connect you with one of our Senior Functional coaches to understand your fitness goals, lifestyle, and offer help and guidance.",
    upgradenow: "Please upgrade now!",
    Targetweight: "Target Weight :",
    fasting: "Fasting Sugar :",
    nonfating: "Non Fasting Sugar :",
    systolicBP: "Systolic BP : ",
    diastolicBP: "Diastolic BP : ",
    BPM: "BPM (optional) : ",
    chngelang: "Change your language",
    upgradeplanmsg: "Currently you are a free user, you need to upgrade plan to use this feature",
    yes: "YES",
    no: "NO",
    replacemsg: "Are you sure , you want to replace",
    replacemeal: "Replace Meal",
    healthindexmsg: "Kindly Upgrade your Plan to get more Accurate Health Index",
    coachalertmsg: "Still not sure what plan to go with, get your first consultation free with us. Click OK to receive call from our specialist in next 2 business days.",
    whrnovalue: "You've not entered WHR value yet. Please add value.",
    Skipfornow:"Skip for Now",
    changelanguage:"Change your language",
    
    no: 'non'
}