export default hindi = {
    Home: "होम",
    Plans:"प्लान्स",
    Message:"मैसेज",
    LNF_Shop:"LNF शॉप",
    profile: "प्रोफ़ाइल",
    yourplan: "तुम्हारा प्लान",
    progress: "प्रोग्रेस",
    grocerylist: "ग्रोसरी लिस्ट",
    LNFshop: "LNF शॉप",
    lang: "भाषा",
    goals: "गोल्स ",
    gratitude: "ग्रैटिट्यूड",
    chatwithcoach: "चैट विद कोच!",
    reminder: "रिमाइंडर",
    blog: "ब्लॉग",
    customersupport: "कस्टमर सपोर्ट",
    faq: "FAQ",
    leadershipboard: "लीडरशिप बोर्ड",
    medicalinformation: "मेडिकल इनफार्मेशन",
    ChangeYourCoach: "अपना कोच चेंज करें",
    deleteaccount: "डिलीट अकाउंट",
    logout: "लॉग आउट",
    TermsandConditions: "नियम एवं शर्तें",
    no: 'non',
    hello: "हैलो",
    Upgrade: "अपग्रेड",
    UnlocktheCoaches: "अनलॉक द कोचेस",
    Unlockover100mealandexerciseplans: "100+ मील और एक्सरसाइज प्लान्स को अनलॉक करें",
    Monitoryourhealth: "अपनी हेल्थ को मॉनिटर करें",
    FirstConsultationfree: "पहला कंसल्टेशन फ्री",
    Unlimitedchatwithcoach: "कोच के साथ अनलिमिटेड चैट",
    ConsultationCallspermonth: "1 कंसल्टेशन कॉल प्रति माह",
    Redeem: "रिडीम",
    pointstobookextraconsultation: "एक्स्ट्रा कंसल्टेशन बुक करने के लिए पॉइंट्स",
    ChooseYourPlan: "अपना प्लान चुनें",
    Bythisupgradeyouwillgetallfeatures: "इस अपग्रेड से आपको सभी फीचर्स मिलेंगे",
    UpgradePlan: "अपग्रेड प्लान",
    MealPlan: "नुट्रिशन प्लान",
    ExercisesPlan: "फिटनेस प्लान",
    Plans: "प्लान्स",
    Coach: "कोच",
    Doctor: "डॉक्टर ",
    YourPersonalHealthAssistant: "आपका पर्सनल हेल्थ असिस्टेंट",
    AddRatings: "रेटिंग्स ऐड करें",
    Morecallispending: "1 कॉल पेंडिंग है।",
    Scheduleacall: "कॉल शेड्यूल करें",
    MyProfile: "मेरी प्रोफाइल",
    LastUpdatedat: "आखिरी बार अपडेट किया गया ",
    TotalPoints: "टोटल पॉइंट्स",
    Bio: "बायो",
    Location: "लोकेशन",
    BasicInformation: "बेसिक इनफार्मेशन",
    PaymentDetails: "पेमेंट विवरण",
    Writesomethingaboutyourself: "अपने बारे में कुछ लिखो",
    HeightWeightAgeGenderActivity: "हाइट, वेट ,आयु, जेंडर, एक्टिविटी ",
    YourPaymentDetails: "आपका पेमेंट विवरण",
    EditProfile: "प्रोफ़ाइल एडिट करें",
    Name: "नाम",
    Foodtype: "फ़ूड टाइप",
    Exerciseintensity: "एक्सरसाइज इंटेंसिटी",
    Height: "हाइट",
    Weight: "वेट ",
    Age: "आयु",
    Submit: "सबमिट ",
    Skip: "स्किप",
    Ok: "ओके",
    HavingabadDay: "दिन बड़ा खराब गुज़र रहा है?",
    Pleaseentergratitude: "कृपया ग्रैटिट्यूड एंटर करें",
    DontworryThefuturebelongstothosewhobelieveinthebeautyoftheirdreams: "डोंट वरी! भविष्य उनका है जो अपने सपनों की सुंदरता पर विश्वास करते हैं।",
    RelaxThinkoftomorrow: "रिलैक्स ! कल के बारे में सोचो, अतीत को सुधारा नहीं जा सकता।",
    NoworriesYesterday: "नो वरीज ! बीता हुआ कल हमारे पास रिकवर के लिए नहीं है, लेकिन कल हमारे जीतने या हारने के लिए है।",
    Itsok: "इट्स ओके अगर आज आपका दिन नहीं था , कल एक नया दिन और है।",
    NoProblem: "नो  प्रॉब्लम ! कल अलग होगा।",
    Good: "गुड! लेकिन आप अभी भी बेहतर कर सकते हैं।",
    YouaregettingcloserKeepitup: "आप करीब आ रहे हैं। इसे जारी रखें।",
    GreatThink: "ग्रेट! सोचें कि आप कर सकते हैं और आप इसे कर सकते हैं। आपके थॉट्स ही आपकी लाइफ हैं।",
    Motivate: "खुद को मोटीवेट करें, आप महान बन सकते हैं।",
    GoodBeall: "गुड! वह सब बनो जो तुम बन सकते हो।",
    WellDoneKeepItUp: "वेल डन ! इसे जारी रखें।",
    Congratulationssoveryproudofyou: "कांग्रेचुलेशन! हमें आप पर बहुत गर्व है!",
    CongratulationsTodayisyourday: "कांग्रेचुलेशन! आज आपका दिन है। आप बहुत अच्छा कर सकते हैं पर आप बहुत दूर हैं!",
    Cheers: "चीयर्स! खुद की मेहनत का फल सबसे मीठा होता है।",
    ExerciseProgress: "एक्सरसाइज प्रोग्रेस",
    TodaysExercise: "टुडेज एक्सरसाइज",
    TodaysMeal: `टुडेज मील`,
    SleepProgress: "स्लीप प्रोग्रेस",
    WeeklyOverview: "वीकली ओवरव्यू ",
    HydrationProgress: "हाइड्रेशन प्रोग्रेस",
    FastingProgress: "फास्टिंग  प्रोग्रेस",
    MonetringProgress: "मॉनिटर  प्रोग्रेस",
    TodaysMood: `टुडेज मूड`,
    TodaysMonitor: `टुडेज मॉनिटर`,
    MoodTitle: "मूड",
    Monitoring: "मॉनिटरिंग ",
    Hydration: "हाइड्रेशन",
    Fasting: "फास्टिंग",
    MoodText: "मूड",
    Sleep: "स्लीप",
    ExerciseText: "एक्सरसाइज",
    totalpointstext: "आपके 21 फ्री रिवॉर्ड पॉइंट्स  टोटल स्कोर में ऐड कर दिए गए हैं",
    AsyouareaPaidUseryoucannotupgradeplan: "आप पेड यूजर/कॉर्पोरेट हैं,आप प्लान अपग्रेड नहीं कर सकते!",
    SetWHR: "सेट वेस्ट टू हिप रेश्यो",
    YourWaisttoHipRatiois: "आपका वेस्ट टू हिप रेश्यो है ",
    lowRisk: "लो रिस्क ",
    hignRisk: "हाई रिस्क ",
    YourReportsWillBeVisibleHere: "आपकी रिपोर्ट यहां दिखाई देंगी",
    TodaysMeal: "टुडेज मील",
    TodaysSleep: "टुडेज स्लीप",
    ElitePlan: 'एलीट प्लान',
    CustomerSupport: "कस्टमर सपोर्ट",
    CustSupportText: "कृपया नीचे दिया गया फॉर्म भरें और हम जल्द से जल्द आपसे कांटेक्ट करेंगे।",
    ProgressChart: "प्रोग्रेस चार्ट",
    AllTime: "ऑल टाइम",
    ThisMonth: "इस महीने",
    CurrentWeight: "करंट वेट :",
    TargetWeight: "टारगेट वेट :",
    Cancel: "कैंसिल",
    YourWellnessWithOurFunctionalHealthPillars: "आपकी वैलनेस हमारे हेल्थ पिल्लर्स के साथ",
    DigitalMateToResetYourHabits: "डिजिटलमेट आपकी आदतों को रीसेट करेगा",
    PatientCenteredCare: "पेशेंट - सेण्टरेड  केयर ",
    TrackYourHealthMetricsRealtime: "अपने रीयलटाइम हेल्थ मेट्रिक्स को ट्रैक करें",
    SetShareGoalWithYourPersonalCoaches: "अपने फंक्शनल कोचेस के साथ गोल्स सेट और शेयर करें",
    NoCalorieCounting: "नो कैलोरी काउंटिंग",
    NoFillingFoodLogs: "नो फिलिंग फूड लॉग्स",
    NoFadDiet: "नो फैड डाइट",
    NoGym: "नो जिम",
    GetNotified: "गेट नोटफाइड ",
    GetStarted: "गेट स्टार्टेड!",
    Next: "नेक्स्ट",
    pleasespecif: "कृपया स्पेसफाइ करें:",
    Register: "रजिस्ट्रेशन करें",
    Login: "लॉग इन करें",
    AreyouaCorporateUser: "क्या आप कॉर्पोरेट यूजर हैं ?",
    Hey: "हे!",
    Gladtomeetyou: "आपसे मिलकर खुशी हुई",
    SignIn: "साइन-इन करें",
    Pleaseenteryourcredentialstocontinue: "कृपया जारी रखने के लिए अपनी क्रेडेंटिअल्स एंटर करें।",
    BysigningIaccepttheTermConditions: "साइनिंग  करके, मैं नियम और शर्तें स्वीकार करता/करती  हूं",
    AgredSignIn: "एग्री और साइन इन करें",
    DonthaveanaccountCreateAccount: "अकाउंट  नहीं है? अकाउंट बनाएं",
    EnterEmailIdPhoneNumber: "ईमेल आईडी/फोन नंबर एंटर  करें",
    validmobilenumber: "कृपया वैलिड मोबाइल नंबर एंटर  करें",
    validemailaddress: "कृपया वैलिड ईमेल पता दर्ज करें",
    EnterPassword: "पासवर्ड एंटर करें",
    EnterEmailId: "ईमेल आईडी दर्ज करें",
    Enterphneno: "फोन नंबर दर्ज करें",
    ForgotPassword: "फॉरगॉट पासवर्ड? ",
    PleaseenteryourCorporateId: "कृपया अपना कॉर्पोरेट आईडी दर्ज करें।",
    Createyouraccount: "अकाउंट बनाएं",
    Pleaseenteryourdetailstouseourapp: "कृपया हमारे ऐप का उपयोग करने के लिए अपनी डिटेल्स एंटर करें",
    AgreeSignUp: "एग्री और साइन अप करें",
    EnterPassword: "पासवर्ड एंटर करें",
    ConfirmPassword: "पासवर्ड कन्फर्म करें",
    Pleaseenteryourname: "कृपया अपना नाम एंटर करें",
    Pleaseentervalidmobilenumber: "कृपया वैलिड मोबाइल नंबर एंटर करें",
    Pleaseentervalidconfirmpassword: "कृपया कन्फर्म पासवर्ड एंटर करें",
    Pleasematchpasswordandconfirmpassword: "कृपया पासवर्ड मैच करें और कन्फर्म करें",
    ForgotPassword: "फॉरगॉट  पासवर्ड ",
    Submit: "सबमिट",
    EnterNewPassword: "नया पासवर्ड एंटर  करें",
    Pleasematchemailaddressandemailaddress: "कृपया ईमेल एड्रेस मैच करें और ईमेल एड्रेस री-एंटर  करें",
    Pleasematchmobilenumberandentermobilenumber: "कृपया मोबाइल नंबर मैच करें और मोबाइल नंबर री-एंटर करें",
    ReEnterYourEmailAddress: "आपना ईमेल एड्रेस री-एंटर करें",
    ReEnterYourMobileNumber: "अपना मोबाइल नंबर री-एंटर करें",
    EnterMobileNumber: "मोबाइल नंबर एंटर करें",
    EnterEmailAddress: "ईमेल एड्रेस एंटर करें",
    ConfirmMobileNumber: "मोबाइल नंबर कन्फर्म करें",
    // ConfirmEnterEmailAddress: "ईमेल एड्रेस  कन्फर्म करें",
    ConfirmEnterEmailAddress: "ईमेल एड्रेस कन्फर्म करें",
    Getnotificationsonyourphoneforanyalertsoractivities: "किसी भी अलर्ट या एक्टिविटीज के लिए अपने फ़ोन पर नोटिफिकेशन्स  प्राप्त करें",
    NameError: "नाम ब्लैंक नहीं हो सकता या उसमें स्पेशल करैक्टर और नंबर नहीं हो सकते!",
    MobileError: "इनवैलिड मोबाइल नंबर!",
    ConfirmMobileError: "मोबाइल और कन्फर्म मोबाइल एक ही होना चाहिए! ",
    EmailError: "इनवैलिड ईमेल एड्रेस!",
    ConfirmEmailError: "ईमेल एड्रेस  और कन्फर्म ईमेल एड्रेस  एक ही होना चाहिए!",
    PasswordError: "पासवर्ड ब्लैंक नहीं हो सकता!",
    RePasswordError: "कन्फर्म पासवर्ड ब्लैंक नहीं हो सकता!!",
    ConfirmError: "पासवर्ड और कन्फर्म पासवर्ड एक ही होना चाहिए!",
    OTPVerification: "ओटीपी वेरिफिकेशन ",
    DidnreceivecodeRequestagain: "कोड प्राप्त नहीं हुआ? फिर से रिक्वेस्ट करें",
    VerifySignIn: "वेरीफाई और साइन इन करें",
    Wehavesentthecodeto: "हमने कोड भेज दिया है",
    AddReportLinks: "रिपोर्ट लिंक ऐड करें",
    AddFiles: "फाइल्स ऐड करें",
    UploadReports: "रिपोर्ट्स अपलोड करें",
    UploadReports: "रिपोर्ट्स अपलोड करें",
    YourLink: "योर लिंक...",
    Description: "लिंक डिस्क्रिप्शन..",
    UploadAttachments: "अटैचमेंट अपलोड करें ",
    AttachmentDescriptionHere: "अटैचमेंट  का डिस्क्रिप्शन ऐड करें",
    Youcannotupload5: "आप एक फ्री यूजर हैं इसलिए आप 5 से अधिक लिंक अपलोड नहीं कर सकते",
    Youcannotuploadfiles1: "आप एक फ्री यूजर हैं इसलिए आप 1 से अधिक फाइल अपलोड नहीं कर सकते",
    OpenCamera: "कैमरा ओपन करें",
    TotalPoints: "टोटल पॉइंट्स ",
    PointslastsyncedonToday: "पॉइंट्स पिछली बार सिंक हुए थे ",
    RedeemPoints: "रिडीम पॉइंट्स",
    Datahasnotbeenentered: "डेटा एंटर नहीं किया गया है!",
    Wellprovidenutritional: "हम नुट्रिएंट्स से भरपूर नुट्रिशन प्लान्स  प्रोवाइड करेंगे, डेली फिटनेस प्लान्स को करना इजी बनाएंगे और आर्टिकल प्रोवाइड करेंगे जो सीखने पर फोकस करते हैं न कि स्टार्विंग पर.",
    Proceed: "आगे बढ़ें ",
    Welcome: "वेलकम",
    PreparingYourPersonalizedMealPlan: "अपनी पर्सनलाइज्ड  मील प्लान  तैयार करना ..",
    PreparingYourPersonalizedExercisePlan: "अपनी पर्सनलाइज्ड एक्सरसाइज प्लान तैयार करना ..",
    AssigningyouaFunctionalCoach: "आपको फंक्शनल कोच असाइन करना..",
    Ourpreventivehealth: "हमारा प्रिवेंटिव हेल्थ प्रोग्राम पावर ऑफ़ 7  पर बेस्ड है। यह एक दिन में केवल 7 मिनट लेता है",
    Readytocommit: "लास्ट हैबिट्स के निर्माण को  कमिट करने लिए  रेडी |",
    RecommendedPlansforyou: "कस्टमाइजेबल डाइट प्लान",
    Basedonyourfitnessgoals: "आपके फिटनेस गोल्स के आधार पर",
    CustomizableDietPlan: "कस्टमाइजेबल डाइट प्लान",
    CustomizableReminders: "कस्टमाइजेबल रिमाइंडर",
    YourCoachAssistantNutritionist: "आपका कोच, असिस्टेंट नूट्रिशनिस्ट",
    OurAI: "हमारा एआई पावर्ड प्लान आपके वेट गोल तक पहुंचने में आपकी हेल्प करेगा",
    SmartDiet: "स्मार्ट डाइट और वर्कआउट प्लान",
    Starts: "₹3500 प्रति माह से शुरू",
    Skipfornow: "अभी के लिए स्किप करें >>",
    ExploreSmart: "स्मार्ट एक्सप्लोर करें",
    HealthIndex: "हेल्थ इंडेक्स ",
    SwipeUpto: "कुछ प्रश्नों के उत्तर देने और अपने हेल्थ इंडेक्स में सुधार करने के लिए ऊपर की ओर स्वाइप करें",
    SureLogout: "क्या आप लॉगआउट करना चाहते हैं?",
    Logout: "लॉगआउट?",
    UpgradePlanText: "वर्तमान में आप एक फ्री यूजर हैं, आप प्लान अपग्रेड करना चाहते हैं?",
    Top5goals: " यहां आपके टॉप 5 गोल्स हैं:",
    Goals: "गोल्स",
    Add: "ऐड",
    Gratification: "ग्रैटिफिकेशन",
    Gratefull: "यहां कुछ चीज़ें दी गई हैं जिनके लिए आप आभारी हैं:",
    PaymentGateway: "पेमेंट गेटवे",
    BasicSubscription: "बेसिक सब्सक्रिप्शन",
    SubscriptionAmount: "सब्सक्रिप्शन अमाउंट ",
    HaveACouponCode: "क्या आपके पास कूपन कोड है?",
    BuyWith: "बाइ विद ",
    WaisttoHipRatioGraph: "वेस्ट टू हिप रेश्यो ग्राफ",
    WaisttoHipRatio: "वेस्ट टू हिप रेश्यो",
    AWaistCircumference: "A : वेस्ट सरकम्फरेन्स",
    BHipCircumference: "B : हिप सरकम्फरेन्स",
    Waist: "वेस्ट*",
    Hip: "हिप*",
    EnterYourWaistValueininch: "इंच में अपनी वेस्ट वैल्यू  एंटर करें",
    EnterYourHipValueininch: "इंच में अपना हिप वैल्यू  एंटर करें",
    YourWaistToHipRatiois: "आपका वेस्ट टू हिप रेश्यो है: ",
    WHRGraph: "WHR ग्राफ",
    WHR2: " WHR (वेस्ट टू हिप रेश्यो है)",
    Psychology: "साइकोलॉजी",
    PsychologyIndexhasbeensubmittedsuccessfully: "साइकोलॉजी इंडेक्स सफलतापूर्वक सबमिट हो गयी है।",
    TotalScore: "टोटल स्कोर",
    PsychologyValidation: "कृपया सभी प्रश्नों के उत्तर दें",
    Pain: "पेन ",
    Enterreson: "पेन का कारण एंटर करें",
    RatingScale: "0 - 10 पेन रेटिंग  स्केल ",
    None: "नन",
    Mild: "माइल्ड",
    Moderate: "मॉडरेट",
    Severe: "सीवियर",
    Save: "सेव",
    SwipeUp: "कुछ प्रश्नों के उत्तर देने के लिए ऊपर स्वाइप करें और अपने हेल्थ इंडेक्स में सुधार करें",
    msg1: "हे! यह स्क्रीन नियमित रूप से पावर ऑफ़ 7 का रिकॉर्ड रखती है!",
    msg2: "अपनी आज की प्रगति के अनुसार इनमें से किसी एक विकल्प का चयन करें",
    msg3: "फिर अपनी साप्ताहिक प्रगति को ट्रैक करने के लिए यहां बटन दबाएं",
    monitoringmsg3: "वीकली प्रोग्रेस ट्रैकिंग सुविधा जल्द ही उपलब्ध होगी।",
    mealmsg1: "पहले से प्लान बनाएं और ट्रैक करें कि आप क्या और कब खा रहे हैं|",
    mealmsg2: "आप योजनाओं पर जा सकते हैं",
    mealmsg3: "मील प्लान और फिर टैप करें",
    mealmsg4: "मील बदलने के लिए आइकन",
    mealmsg5: "आपको मील पसंद आया? आइकन पर क्लिक करके बताएं",
    mealmsg6: "और हम उस मील को एक सप्ताह तक दोहराएंगे।",
    Exercisemsg1: "अपने शरीर को अपनी डेली एक्टिविटी के सामान्य स्तर से अधिक इंटेंसिटी से इंगेज करें।",
    Exercisemsg2: "आप प्लान पर जा सकते हैं",
    Exercisemsg3: "एक्सरसाइज प्लान और फिर टैप करें",
    Exercisemsg4: "एक्सरसाइज को बदलने के लिए",
    sleep: "नींद आराम की अवधि है जो दिमाग को तरोताजा करती है और शरीर की मरम्मत करती है",
    hydration: "टिशू के लिए पर्याप्त तरल पदार्थ (जैसे पानी, चाय, कॉफी आदि) प्रोवाइड करना।",
    fasting: "हेल्थ, रिचूअलिस्टिक, एथिकल , या नैतिक उद्देश्यों के लिए भोजन या पेय या दोनों से परहेज",
    Mood: "माइंड की कौन्सियस स्टेट या प्रेडोमिनैंट इमोशन।",
    Observing: "गतिविधियों का ऑब्जरवेशन और रिकॉर्डिंग।",
    deleteacc: "क्या आप डिलीट करना  चाहते हैं ",
    More: "मोर",
    AsyouarePregnant: "चूंकि आप गर्भवती/प्रसवोत्तर/स्तनपान कराने वाली हैं, इसलिए आपको पेड प्लान लेने की सलाह दी जाती है।",
    Diabetes: "चूंकि आपको इंसुलिन के साथ डायबिटीज  है, इसलिए आपको पेड प्लान लेने की सलाह दी जाती है।",
    Insulin: "जैसा कि आप इंसुलिन पर हैं, आपको पेड प्लान लेने की सलाह दी जाती है।",
    FeatureComingSoon: "फ़ीचर जल्द ही आ रहा है...",
    ThisfeatureforPaidCorporateUser: "यह फीचर केवल पेड/कॉर्पोरेट यूजर के लिए उपलब्ध है। अपग्रेड करने के लिए कृपया ओके पर क्लिक करें",
    Reminder: "रिमाइंडर",
    TrackFoodReminder: "ट्रैक फ़ूड रिमाइंडर",
    WaterReminder: "वाटर रिमाइंडर",
    ExerciseReminder: "एक्सरसाइज रिमाइंडर",
    threeMealsatdifferenttimes: "3 मील्स, डिफरेंट टाइम्स",
    Remindmeevery3Hour: "रिमाइंड मी एव्री 3 घंटे पर",
    Remindmeeverydayat: "रिमाइंड मी एवरीडे 7:30 PM पर",
    comments: "कमैंट्स (ऑप्शनल)",
    Message: "मैसेज",
    EnteryourGoal: "अपना गोल एंटर करें",
    EnterGratification: "अपना ग्रैटिफिकेशन एंटर करें",
    GroceryList: " आपकी ग्रोसरी लिस्ट आइटम",
    GroceryListTitle: "ग्रोसरी लिस्ट",
    AddGroceries: "ऐड ग्रोसरी",
    Profiling: "प्रोफाइलिंग",
    LookslikeyoureinterestedingainingweightusingLNF: "ऐसा लगता है कि आप एलएनएफ का उपयोग करके वेट गेन करने में रुचि रखते हैं।",
    Wehaveidealplanforyou: "हमारे पास आपके लिए आइडियल प्लान है।",
    LookslikeyouinterestedinlosingweightusingLNF: "ऐसा लगता है कि आप एलएनएफ का उपयोग करके वेट लूज़ करने में रुचि रखते हैं।",
    LNFisnotcurrentlydesignedtoreachtheenteredgoalweight: "LNF को वर्तमान में दर्ज किए गए टारगेट वेट  तक पहुंचने के लिए डिज़ाइन नहीं किया गया है। आपका टारगेट वेट  बीच में होना चाहिए-",
    PleaseedityourTargetweighttoContinue: "कृपया जारी रखने के लिए अपना टारगेट वेट एंटर करें",
    Next: "नेक्स्ट",
    FreeUser: "फ्री यूजर",
    paidUser: "पेड यूजर",
    Select: "सेलेक्ट",
    CoporateIDEroor: "कॉर्पोरेट आईडी एम्प्टी नहीं हो सकती!",
    LowGIFruitsandVegatables: "लो GI फल और सब्जियां",
    callmsg: "क्या मैं आपके लिए कॉल शेड्यूल कर सकता हूँ?",
    bysignin: "मैं साइनिंग करके स्वीकार करता हूं,",
    termsandcondition: "टर्म्स और कंडीशंस",
    donthaveanaccount: "कोई अकाउंट नहीं है? ",
    craeteone: "अकाउंट बनाएं",
    didnotreceivecode: "कोड रिसीव नहीं हुआ? ",
    requestagain: "पुनः रिक्वेस्ट करें",
    letsGo: "लेट्स गो",
    and: "और",
    privacypolicy: "प्राइवेसी पालिसी, ",
    includingusage: "कूकीज के यूसेज के साथ",
    forgetpassword: "पासवर्ड भूल गए!",
    forgetmailmsg: "हम आपके रजिस्टर्ड ईमेल एड्रेस पर पासवर्ड रीसेट करने के लिए वेरिफिकेशन लिंक भेजेंगे। कृपया अपना मेल इनबॉक्स चेक करें।",
    freeuser: "फ्री यूजर",
    paiduser: "पेड यूजर",
    corporate: "कॉर्पोरेट",
    hindi: "हिंदी",
    english: "इंग्लिश",
    freecoachmsg: "फंक्शनल कोचिंग का यूज करने के लिए, कृपया अपग्रेड करें।\nफिर हम आपको आपके फिटनेस गोल्स , लाइफस्टाइल को समझने और सहायता एवं गाइडेंस प्रदान करने के लिए हमारे सीनियर फंक्शनल कोचेस से जोड़ेंगे.",
    upgradenow: "कृपया अभी अपग्रेड करें!",
    Targetweight: "टारगेट वेट :",
    fasting: "फास्टिंग शुगर :",
    nonfating: "नॉन फास्टिंग शुगर :",
    systolicBP: "सिस्टोलिक BP : ",
    diastolicBP: "डायास्टोलिक BP : ",
    BPM: "BPM (optional): ",
    chngelang: "अपनी भाषा बदलो",
    upgradeplanmsg: "वर्तमान में आप फ्री यूजर हैं, आपको इस फीचर को यूज़ करने के लिए प्लान को अपग्रेड करना होगा",
    yes: "हां",
    no: "नहीं",
    replacemsg: "क्या आप वाकई रिप्लेस करना चाहते हैं-",
    replacemeal: "रिप्लेस मील",
    healthindexmsg: "एक्यूरेट हेल्थ इंडेक्स प्राप्त करने के लिए कृपया अपने प्लान को अपग्रेड करें",
    coachalertmsg: "अभी भी निश्चित नहीं है कि किस प्लान के साथ जाना है, अपना पहला कंसल्टेशन हमसे निःशुल्क प्राप्त करें। अगले 2 व्यावसायिक दिनों में कॉल प्राप्त करने के लिए ओके पर क्लिक करें",
    whrnovalue: "आपने अभी तक WHR वैल्यू एंटर नहीं किया है. कृपया वैल्यू ऐड करें .",
    Skipfornow: "स्किप करे",
    changelanguage: "अपनी भाषा बदलें"



}